### ISSUE TITLE
Debian/Ubuntu images

### ISSUE THREAD

**Issue by jonmosco** [redteam-project/red-container#3]
Will Debian/Ubuntu base images be allowed/accepted, or is the focus on Fedora (RPM) based images?

**Comment by trevorbryant** [comment]
Commenting since it's been a couple of days.

I asked the same question about consistency with Fedora / Enterprise Linux. The answer I received was that any images are welcome so long they meet the docker "standards".

That being said, I've been creating and testing Alpine images for minimal size and optimization.

**Comment by trevorbryant** [comment]
@jonmosco at this point Debian/Ubuntu base images have been allowed and accepted.

Build on!

**Comment by jason-callaway** [comment]
+1, @trevorbryant is correct. Any base image that works is acceptable, but smaller is preferred. We'd like to avoid whole-distro images like [kali-linux-docker](https://hub.docker.com/r/kalilinux/kali-linux-docker), though.
